// Code generated by go generate; DO NOT EDIT

package models

type GetProfileData struct {
	SharableAllPublish                 bool   `json:"sharable_all_publish"`
	AllowEventsAgreed                  bool   `json:"allow_events_agreed"`
	AllowProfileInfoCollectAgreed      bool   `json:"allow_profile_info_collect_agreed"`
	NeedVerify                         bool   `json:"need_verify"`
	TalkBirthdayActive                 bool   `json:"talk_birthday_active"`
	Sharable                           bool   `json:"sharable"`
	NameSearchable                     bool   `json:"name_searchable"`
	ContentSearchable                  bool   `json:"content_searchable"`
	Type                               string `json:"type"`
	ExposeUpPermission                 string `json:"expose_up_permission"`
	PushNotificationInviteFriendActive bool   `json:"push_notification_invite_friend_active"`
	PushNotificationBirthdayActive     bool   `json:"push_notification_birthday_active"`
	PushNotificationCommentLikeActive  string `json:"push_notification_comment_like_active"`
	ShowHighlightZodiacSign            bool   `json:"show_highlight_zodiac_sign"`
	AbTest                             struct {
		UseFeedFilter bool `json:"use_feed_filter"`
	} `json:"ab_test"`
	ID                           string `json:"id"`
	Vip                          bool   `json:"vip"`
	FriendCount                  int    `json:"friend_count"`
	TaggedActivityViewPermission string `json:"tagged_activity_view_permission"`
	IsBirthday                   bool   `json:"is_birthday"`
	AllowFollowing               bool   `json:"allow_following"`
	StatusObjects                []struct {
		ObjectType string `json:"object_type"`
		Message    string `json:"message"`
	} `json:"status_objects"`
	PushNotificationCommentActive      string `json:"push_notification_comment_active"`
	PushNotificationQnaActivityActive  bool   `json:"push_notification_qna_activity_active"`
	ExposeFolloweePermission           string `json:"expose_followee_permission"`
	PushNotificationFavoriteUserActive bool   `json:"push_notification_favorite_user_active"`
	URISearchable                      bool   `json:"uri_searchable"`
	CommentAllWritable                 bool   `json:"comment_all_writable"`
	DisplayName                        string `json:"display_name"`
	GenderPermission                   string `json:"gender_permission"`
	HighlightZodiacSignPermission      string `json:"highlight_zodiac_sign_permission"`
	PushNotificationFeelingActive      string `json:"push_notification_feeling_active"`
	Name                               string `json:"name"`
	LocationAgreed                     bool   `json:"location_agreed"`
	PushNotificationFollowingActive    bool   `json:"push_notification_following_active"`
	HashedAccountId                    string `json:"hashed_account_id"`
	ShowHighlightBestFriends           bool   `json:"show_highlight_best_friends"`
	TalkProfileSchoolActive            bool   `json:"talk_profile_school_active"`
	BizInfoActive                      bool   `json:"biz_info_active"`
	PushNotificationAlert              bool   `json:"push_notification_alert"`
	HighlightVisitCounterPermission    string `json:"highlight_visit_counter_permission"`
	PushNotificationSuggestActive      bool   `json:"push_notification_suggest_active"`
	AllowActionGraph                   bool   `json:"allow_action_graph"`
	ExposeFriendPermission             string `json:"expose_friend_permission"`
	Gender                             string `json:"gender"`
	DisplayId                          string `json:"display_id"`
	ExposeBookmarkPermission           string `json:"expose_bookmark_permission"`
	ShowHighlightVisitCounter          bool   `json:"show_highlight_visit_counter"`
	MessageAllSendable                 bool   `json:"message_all_sendable"`
	PushNotificationShareActive        string `json:"push_notification_share_active"`
	ProfileUri                         string `json:"profile_uri"`
	TalkProfileActive                  bool   `json:"talk_profile_active"`
	FollowerCount                      int    `json:"follower_count"`
	ServiceUserId                      int    `json:"service_user_id"`
	SuggestFriendExposeActive          bool   `json:"suggest_friend_expose_active"`
	TalkGotostoryActive                bool   `json:"talk_gotostory_active"`
	ActivityCount                      int    `json:"activity_count"`
	DefaultBgId                        int    `json:"default_bg_id"`
	FriendAcceptLevel                  string `json:"friend_accept_level"`
	FirstName                          string `json:"first_name"`
	TalkProfileGenderActive            bool   `json:"talk_profile_gender_active"`
	TalkProfileAddressActive           bool   `json:"talk_profile_address_active"`
	BgImageUrl                         string `json:"bg_image_url"`
	ProfileThumbnailUrl                string `json:"profile_thumbnail_url"`
	ShowHighlightKeywords              bool   `json:"show_highlight_keywords"`
	PushNotificationMessageActive      bool   `json:"push_notification_message_active"`
	TalkProfileCompanyActive           bool   `json:"talk_profile_company_active"`
	LastName                           string `json:"last_name"`
	ProfileImageUrl                    string `json:"profile_image_url"`
	BirthAgreed                        bool   `json:"birth_agreed"`
	IsDefaultProfileImage              bool   `json:"is_default_profile_image"`
	IsTalkUser                         bool   `json:"is_talk_user"`
	HighlightKeywordsPermission        string `json:"highlight_keywords_permission"`
}
