// Code generated by go generate; DO NOT EDIT

package models

type GetSpecificFriends struct {
	ErrorMessage string `json:"error_message"`
	ErrorCode    int    `json:"error_code"`
	Error        string `json:"error"`
}
